// <auto-generated />
using System;
using DenemeCalisma1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenemeCalisma1.Migrations.FirstDbContext
{
    [DbContext(typeof(FirstDbContext))]
    [Migration("20241017235347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DenemeCalisma1.Models.VeriTabani1.Acente", b =>
                {
                    b.Property<int>("AcenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcenteID"));

                    b.Property<string>("AcenteAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IlcelerID")
                        .HasColumnType("int");

                    b.Property<int?>("SehirlerID")
                        .HasColumnType("int");

                    b.Property<string>("VeriTabaniLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeriTabaniServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeriTabaniSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcenteID");

                    b.HasIndex("IlcelerID");

                    b.HasIndex("SehirlerID");

                    b.ToTable("Acenteler");
                });

            modelBuilder.Entity("DenemeCalisma1.Models.VeriTabani1.Ilce", b =>
                {
                    b.Property<int>("IlcelerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlcelerID"));

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SehirlerID")
                        .HasColumnType("int");

                    b.HasKey("IlcelerID");

                    b.HasIndex("SehirlerID");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("DenemeCalisma1.Models.VeriTabani1.Sehir", b =>
                {
                    b.Property<int>("SehirlerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SehirlerID"));

                    b.Property<string>("SehirAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SehirPlakasi")
                        .HasColumnType("smallint");

                    b.HasKey("SehirlerID");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("DenemeCalisma1.Models.VeriTabani1.Acente", b =>
                {
                    b.HasOne("DenemeCalisma1.Models.VeriTabani1.Ilce", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlcelerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DenemeCalisma1.Models.VeriTabani1.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirlerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ilce");

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("DenemeCalisma1.Models.VeriTabani1.Ilce", b =>
                {
                    b.HasOne("DenemeCalisma1.Models.VeriTabani1.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirlerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sehir");
                });
#pragma warning restore 612, 618
        }
    }
}
